import { defaultFont } from "@/common/constant";
import { IAppConfig } from "@/types/app-config";

const _defaultAppConfig: IAppConfig = {
    "$schema-version": 1,
    "playMusic.whenQualityMissing": "lower",
    "playMusic.defaultQuality": "standard",
    "playMusic.clickMusicList": "replace",
    "playMusic.caseSensitiveInSearch": false,
    "playMusic.playError": "skip",
    "playMusic.whenDeviceRemoved": "play",
    "playMusic.defaultVolume": "0.5",
    "normal.taskbarThumb": "window",
    "normal.closeBehavior": "minimize",
    "normal.checkUpdate": true,
    "normal.maxHistoryLength": 30,
    "normal.alwaysOnTop": false,
    "download.defaultQuality": "standard",
    "download.whenQualityMissing": "lower",
    "lyric.enableStatusBarLyric": false,
    "lyric.enableDesktopLyric": false,
    "lyric.alwaysOnTop": false,
    "lyric.lockLyric": false,
    "lyric.showTranslation": "both",
    "lyric.fontData": defaultFont,
    "lyric.fontColor": "#fff",
    "lyric.strokeColor": "#b48f1d",
    "lyric.fontSize": 54,
    "translate.provider": "libretranslate",
    "translate.baiduType": "standard",
    "translate.targetLanguage": "zh",
    "translate.baiduAppId": "",
    "translate.baiduSecretKey": "",
    "translate.baiduLLMAppId": "",
    "translate.baiduLLMApiKey": "",
    "translate.autoSaveTranslation": true,
    "translate.autoTranslateNonChinese": true,
    "shortCut.enableLocal": true,
    "shortCut.enableGlobal": false,
    "download.concurrency": 5,
    "normal.musicListColumnsShown": [],
    "backup.resumeBehavior": "append",
    "normal.language": "zh-CN",
    "musicInfo.searchEngine": "baidu",
    "localMusic.autoRefreshOnFileChange": false,
};


export default _defaultAppConfig;
